"""auto-migration

Revision ID: 5974260b41df
Revises: f0437a233ab0
Create Date: 2025-11-18 12:25:20.750667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5974260b41df'
down_revision = 'f0437a233ab0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_ts', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('time_ts', sa.Time(), nullable=True))
        batch_op.alter_column('date',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('time',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.alter_column('time',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('date',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.drop_column('time_ts')
        batch_op.drop_column('date_ts')

    with op.batch_alter_table('client_tokens', schema=None) as batch_op:
        batch_op.drop_column('expires_at')

    # ### end Alembic commands ###
